name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps: 
    - name: hello-mona 
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - name: hello-script
      run: ${{ github.action_path }}/hello.sh
      shell: bash
